
-------------------------------------------------------------------------------
|        ..          ..                                                       |
|       ####*.      ####.                                                     |
|         `###*.       `#.              MSC Software                          |
|            `###.       #.             ------------                          |
|               `##.     ##                                                   |
|                 `##.   ##                                                   |
|                   `## ##'             A d a m s   C++   S o l v e r         |
|                     ####              Build:   2021.1.0-CL801488            |
|                     ###.              Version: Adams 2021.1                 |
|                    ###`#.                                                   |
|                  .###  `#                                                   |
|                 ####    `#                                                  |
|                ####      #.                                                 |
|              #####       `#           http://www.mscsoftware.com            |
|            .#####                                                           |
|           #####'                                                            |
|           ####                                                              |
|                                                                             |
|    *********************************************************************    |
|    *                                                                   *    |
|    *                      MSC Software Corporation                     *    |
|    *                                                                   *    |
|    *                             A d a m s                             *    |
|    *                                                                   *    |
|    *          Automatic Dynamic Analysis of Mechanical Systems         *    |
|    *                                                                   *    |
|    *********************************************************************    |
|    *                                                                   *    |
|    *                         LEGAL INFORMATION                         *    |
|    *                                                                   *    |
|    *  Warning:  This computer  program is protected  by copyright law  *    |
|    *  and  international  treaties.    Unauthorized  reproduction  or  *    |
|    *  distribution  of this  computer program, or any  portion of it,  *    |
|    *  may result in severe civil and criminal penalties.               *    |
|    *                                                                   *    |
|    *  Copyright (C) 2021 MSC Software Corporation and  its licensors.  *    |
|    *                        All rights reserved.                       *    |
|    *                                                                   *    |
|    *********************************************************************    |
|                                                                             |
|-----------------------------------------------------------------------------|
|                                                                             |
|    *********************************************************************    |
|    *                                                                   *    |
|    *   Local Time: 2022-09-04 19:32:00                                 *    |
|    *    Host Name: USANN-79JKPN3                                       *    |
|    *        Uname: MS Windows NT                                       *    |
|    *      OS Info: 6.2                                                 *    |
|    *         User: ben.thornton                                        *    |
|    *  Customer ID: 042718AA-779156FF                                   *    |
|    *  Current dir: C:\Users\ben.thornton\AppData\Local\Temp\tmpjllfqvax*    |
|    *   Process ID: 43696                                               *    |
|    *                                                                   *    |
|    *********************************************************************    |
|                                                                             |
-------------------------------------------------------------------------------

 command: FILE/MODEL=bearing.adm, OUTPUT_PREFIX=sim_std 

-------------------------------------------------------------------------------
|                                 Model Title                                 |
|=============================================================================|
|                                                                             |
|                       Adams View model name: bearing                        |
|                                                                             |
-------------------------------------------------------------------------------

 command: SIMULATE/DYNAMIC, END=1.0, STEPS=100


  Begin Simulation

  ****** Performing Dynamic Simulation using Gstiff I3 Integrator ******
   The system is modelled with INDEX-3 DAEs.
   The integrator is GSTIFF, CORRECTOR = original
   Integration error =    1.000000E-03

   Simulation   Step          Function     Cumulative    Integration   Elapsed 
   Time         Size          Evaluations  Steps Taken   Order         Time    
   ___________  ___________   ___________  ___________   ___________   ________
   0.00000E+00  5.00000E-04            0            0             1       0.11 


---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
A Not-a-Number (NaN) value was computed for the integration error. This problem may be related to wrong
values computed by user-written subroutines. Please try using the Adams utility subroutine NANINF.
Simulation time is 5.142857143E-03
---- END: ERROR ----


  Dynamic Solution stopped.


  End Simulation
 command: STOP


---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



---- START: ERROR ----
NaN value deteceted in AsMath::step() function.
Simulation time is 5.142857143E-03
---- END: ERROR ----



Finished -----
Elapsed time = 1.85s,  CPU time = 0.36s,  Average CPU load = 19.42%

